### ISSUE TITLE
Console debugging experience when nothing works is not ideal

### ISSUE THREAD

**Issue by iliana** [bottlerocket-os/bottlerocket#385] opened 2019-10-09 18:26 UTC
When trying to view the instance system/console log in the EC2 console:

- [x] ANSI color sequences don't render, so it's very hard to read
- [ ] systemd truncates long lines, but we'd rather have the full output
- [x] Services in the boot path should probably have their stdout/stderr make it to the console as well

**Comment by tjkirch** [comment] 2020-04-14 21:09
Does anyone have an example of truncated log output in the console?  I'm seeing some pretty long lines on a test instance (650+ characters) with no truncation.

**Comment by tjkirch** [comment] 2020-04-15 00:15
Going to close this because the only remaining checkbox is line truncation, which I'm not seeing and someone else confirmed they're not seeing.  We can reopen if we can reproduce.

**Closed by tjkirch** 2020-04-15 00:15 UTC
