### ISSUE TITLE
api: Log specifics of changes to settings

### ISSUE THREAD

**Issue by jhaynes** [bottlerocket-os/bottlerocket#312] opened 2019-09-26 21:33 UTC
When modifying settings via the API, there is no audit logging such that I can see when and by whom a given setting was changed.

**Comment by stmcginnis** [comment] 2022-12-05 17:06
Capturing the "who" may be tricky due to things like SSM access, but it does seem like we should have some sort of audit log. We would need to be very mindful of logging sensitive data though.

**Comment by arnaldo2792** [comment] 2023-04-28 20:13
This is a duplicate of:

https://github.com/bottlerocket-os/bottlerocket/issues/2640

Closing in favor of the most recent issue.

**Closed by arnaldo2792** 2023-04-28 20:13 UTC
Labels: type/enhancement, area/core
