### ISSUE TITLE
kubernetes: bottlerocket doesn't understand the "Exists" taint

### ISSUE THREAD

**Issue by diranged** [bottlerocket-os/bottlerocket#1302] opened 2021-02-06 01:36 UTC
**Platform I'm building on:**
Bottlerocket 1.0.5 on EKS 1.18

**What I expected to happen:**
Kubernetes has an `Exists` taint that has no value key in it. So the CLI argument looks like this:

```
kubelet ... --register-with-taints=MyKey:NoSchedule
```

and a matching Toleration would look like this:

```
tolerations:
  - operator: Exists
    key: MyKey
    effect: NoSchedule
```

However, there is no way to put that into the `settings.kubernetes.node-taints` configuration because the pattern is hard-coded to expect an `Equals` taint: https://github.com/bottlerocket-os/bottlerocket/blob/b5fd55f22d31eea87f2fa4b9491aeb73c12498a2/packages/kubernetes-1.18/kubelet-env#L3

**What actually happened:**
I could not boot up nodes - they failed to parse the key and threw an error.

**Comment by etungsten** [comment] 2021-03-19 21:31
Hi @diranged, 

The `--register-with-taints` argument to kubelet takes a list of taints of the form ` <key1>=<value1>:<effect1>,<key2>=<value2>:<effect2>`. The equal sign is a necessary part of the separators. (See documentation for this argument [here](https://kubernetes.io/docs/concepts/architecture/nodes/#self-registration-of-nodes) and [here](https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet/)).

The problem is that the validation we have for KubernetesTaintValue currently doesn’t allow for an empty taint value. 
https://github.com/bottlerocket-os/bottlerocket/blob/fdb0353df12fa3f710628c81fe3a79aa98d42e6c/sources/models/src/modeled_types/kubernetes.rs#L206-L236

This is being fixed in #1406. Once that’s merged, you should be able to specify taints without values and use `Exists` tolerations. For example, in userdata:

```
[settings.kubernetes.node-taints]
MyKey = ":NoSchedule"
SomeOtherKey = "SomeValue:NoSchedule"
```

**Closed as completed** 2021-03-23 22:06 UTC
Labels: type/bug, area/kubernetes
