### ISSUE TITLE
How to determine why SSM agent is dying?

### ISSUE THREAD

**Issue by nazarewk** [bottlerocket-os/bottlerocket#2624] opened 2022-12-02 15:17 UTC
**Image I'm using:**

`bottlerocket-aws-ecs-1-aarch64-v1.11.1-104f8e0f`

**What I expected to happen:**

Bottlerocket's SSM agent keeps running on ECS node

**What actually happened:**

After some time SSM agent is dying and I cannot do anything except rebooting instance.

**How to reproduce the problem:**

No idea, having the issue when trying to spin Netbird clients in a cluster https://github.com/netbirdio/netbird/issues/598

I cannot find a way to debug the issue, can I enable SSH server on the instance somehow?

**Comment by nazarewk** [comment] 2022-12-05 15:47
I've managed to connect to those failind instances after setting up SSH, but still can't connect through SSM. How can I debug it further? I can find no way to display host/control containers

**Comment by nazarewk** [comment] 2022-12-05 16:11
I've found the root cause at https://github.com/netbirdio/netbird/issues/598#issuecomment-1337629243 , but the question on how to more easily debug operations of bottlerocket components still stands.

**Comment by jpmcb** [comment] 2022-12-05 16:20
> can I enable SSH server on the instance somehow?

You'll find the [documentation on admin containers helpful.](https://github.com/bottlerocket-os/bottlerocket#admin-container) The admin container has an ssh server you can pass your ssh keys to then get onto the host. If you need to explore with higher permissions, once inside the admin container, you can get a root level shell via `sudo sheltie`. From here, you can run things like `journalctl` to see boot logs.

The [`logdog` command](https://github.com/bottlerocket-os/bottlerocket#logs) we provide is also useful for getting a whole tarball of logs on the host.

If this was a kernel panic and you weren't able to boot the host, we also provide [`kdump` support.](https://github.com/bottlerocket-os/bottlerocket#kdump-support)

---

I'm not sure where the ssm-agent writes it's logs but you may also want to [look under `/var/log/amazon/ssm/`](https://docs.aws.amazon.com/systems-manager/latest/userguide/sysman-agent-logs.html). I'm booting a bottlerocket host now to confirm

**Comment by arnaldo2792** [comment] 2022-12-05 20:46
> If this was a kernel panic and you weren't able to boot the host, we also provide [kdump support.](https://github.com/bottlerocket-os/bottlerocket#kdump-support)

Kdump wouldn't be enabled by default in AWS variants. In variants with support for Boot Configs, kdump could be enabled by assigning memory for the crash kernel.

You should be able to see the host-container logs in the "System Logs" available in the AWS EC2 web console. If that doesn't' work, as @jpmcb , you can access your instances through the admin container and further debug with `sudo sheltie`, something like:

```bash
sudo sheltie logdog # creates archive with logs, accessible at /.bottlerocket/support
tar -xf /.bottlerocket/support/bottlerocket-logs.tar.gz # inspect the extracted files from the admin container
```

**Comment by stmcginnis** [comment] 2023-03-02 21:32
I believe this will be improved once the project website is up and https://github.com/bottlerocket-os/project-website/issues/17 is merged. Since the root cause was found, closing this as the only follow on is improving the docs.

**Closed as completed by stmcginnis** 2023-03-02 21:32 UTC
Labels: type/bug, status/needs-triage
