### ISSUE TITLE
SSM Parameter pointing at missing AMI?

### ISSUE THREAD

**Issue by nairb774** [bottlerocket-os/bottlerocket#2617] opened 2022-11-30 21:46 UTC
**Image I'm using:**

Trying to use the Kubernetes 1.22 x86_64 AMI but the SSM parameter seems to point at a missing image.

**What I expected to happen:**

The SSM parameter ` /aws/service/bottlerocket/aws-k8s-1.22/x86_64/latest/image_version` would point to a version (`1.11.1-104f8e0f` right now), which would allo looking up an SSM parameter (`/aws/service/bottlerocket/aws-k8s-1.22/x86_64/1.11.1-104f8e0f/image_id`) which would point to an existing AMI that can be deployed.

**What actually happened:**

The last SSM parameter references an AMI that doesn't seem to exist (or is not yet public?).

**How to reproduce the problem:**

In the us-east-1 region:

```

$ aws ssm get-parameter --name /aws/service/bottlerocket/aws-k8s-1.22/x86_64/latest/image_version
{
    "Parameter": {
        "Name": "/aws/service/bottlerocket/aws-k8s-1.22/x86_64/latest/image_version",
        "Type": "String",
        "Value": "1.11.1-104f8e0f",
        "Version": 12,
        "LastModifiedDate": "2022-11-30T12:48:37.203000-08:00",
        "ARN": "arn:aws:ssm:us-east-1::parameter/aws/service/bottlerocket/aws-k8s-1.22/x86_64/latest/image_version",
        "DataType": "text"
    }
}

$ aws ssm get-parameter --name /aws/service/bottlerocket/aws-k8s-1.22/x86_64/1.11.1-104f8e0f/image_id
{
    "Parameter": {
        "Name": "/aws/service/bottlerocket/aws-k8s-1.22/x86_64/1.11.1-104f8e0f/image_id",
        "Type": "String",
        "Value": "ami-0776799044a14839c",
        "Version": 1,
        "LastModifiedDate": "2022-11-30T12:37:43.323000-08:00",
        "ARN": "arn:aws:ssm:us-east-1::parameter/aws/service/bottlerocket/aws-k8s-1.22/x86_64/1.11.1-104f8e0f/image_id",
        "DataType": "text"
    }
}

$ aws ec2 describe-images --filters "Name=image-id,Values=ami-0776799044a14839c"
{
    "Images": []
}

```

**Comment by nairb774** [comment] 2022-11-30 21:53
Looks like the 1.21 images are impacted as well:

```
$ aws ssm get-parameter --name /aws/service/bottlerocket/aws-k8s-1.21/x86_64/1.11.1-104f8e0f/image_id
{
    "Parameter": {
        "Name": "/aws/service/bottlerocket/aws-k8s-1.21/x86_64/1.11.1-104f8e0f/image_id",
        "Type": "String",
        "Value": "ami-0076501e23cf0caa8",
        "Version": 1,
        "LastModifiedDate": "2022-11-30T12:37:23.477000-08:00",
        "ARN": "arn:aws:ssm:us-east-1::parameter/aws/service/bottlerocket/aws-k8s-1.21/x86_64/1.11.1-104f8e0f/image_id",
        "DataType": "text"
    }
}

$ aws ec2 describe-images --filters "Name=image-id,Values=ami-0076501e23cf0caa8"
{
    "Images": []
}
```

**Comment by stmcginnis** [comment] 2022-11-30 22:20
Thanks for raising this! Checking into how this happened yet, but it does look like there was an error marking the AMIs public. The SSM data is being rolled back to v1.11.0 for now and will be updated as soon as the AMIs can be verified as actually public.

**Comment by kdaula** [comment] 2022-12-01 02:09
Thanks again for raising this issue. We have addressed the issue. Bottlerocket users who launched EC2 instances by querying SSM parameters to get the latest AMI ID, observed launch failures between 20:47 UTC and 22:01 UTC. This was caused by an error where a yet to be released version was incorrectly marked as latest in SSM and was addressed by reverting the latest to point to the correct version.

**Closed as completed by kdaula** 2022-12-01 02:09 UTC
