### ISSUE TITLE
Availability of Bottlerocket in China (Beijing) (cn-north-1) or China (Ningxia) (cn-northwest-1) region.

### ISSUE THREAD

**Issue by rajboruah** [bottlerocket-os/bottlerocket#1920] opened 2022-01-22 15:03 UTC
### Discussed in https://github.com/bottlerocket-os/bottlerocket/discussions/1919

<div type='discussions-op-text'>

<sup>Originally posted by **rajboruah** January 22, 2022</sup>
Hi,

As per https://docs.aws.amazon.com/eks/latest/userguide/launch-node-bottlerocket.html - "You can't deploy to the following regions: China (Beijing) (cn-north-1) or China (Ningxia) (cn-northwest-1)." May I get clarity on this please ? We want to use Bottlerocket as part EKS's _managed node group_ but as I mentioned above, the images does not seem to be available in China (Beijing) (cn-north-1) or China (Ningxia) (cn-northwest-1). Can you please confirm on this please ?</div>

**Comment by zmrow** [comment] 2022-01-24 16:05
Hi there!  We're excited to make Bottlerocket available in China, but I don't have any solid dates to share at this time.

Closing this as a duplicate of  #1255 - please follow that issue for updates! :)

**Closed as completed by zmrow** 2022-01-24 16:05 UTC
