### ISSUE TITLE
[Artifactory compatibility] add support for v2 schema 1 images

### ISSUE THREAD

**Issue by bcressey** [bottlerocket-os/bottlerocket#1234] opened 2020-12-09 00:08 UTC
**Image I'm using:**
v1.0.2

**What I expected to happen:**
Per customer bug report, kubelet should have pulled a v2 schema 1 image.

**What actually happened:**
Pod failed with an ImagePullBackOff error.

**How to reproduce the problem:**
Launch a pod that references a v2 schema 1 image.

**Comment by bcressey** [comment] 2020-12-09 00:09
@samuelkarp suggested that there might be a flag in containerd-cri or a small code change needed.

**Comment by samuelkarp** [comment] 2020-12-09 00:20
https://github.com/containerd/cri/blob/3a1c3b3b4b1ec10ab59723ba72ca2cbbc97ab6fe/pkg/server/image_pull.go#L110 already shows the schema 1 conversion functional option getting added to the Pull call in the containerd 1.3 branch.  Assuming that code is present in our release (I suspect it is), we'll need to reproduce this problem to debug what else is going on.

**Comment by samuelkarp** [comment] 2020-12-19 00:12
I'm not able to reproduce this issue with Bottlerocket 1.0.4.  Here are the steps that I used to try and reproduce it:

1. Install a very old version of Docker that only supports v2 schema 1 (Docker 1.9 or older)
2. Pull an image from Docker Hub, which will down-convert to v2 schema 1 (I used the `busybox` library image)
3. Push the image to an ECR repository and verify that the media type is uploaded as expected (`application/vnd.docker.distribution.manifest.v1+prettyjws`, see details below)
4. Verify the manifest has `"schemaVersion": 1` (see details)
5. Run a pod with the image, successfully (`kubectl run`)
6. On the Bottlerocket node, inspect the image and verify that it has the correct media type

<details>

<summary>Expand to see shell sessions</summary>

```
# On a host with Docker 1.9.1

$ docker version
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   a34a1d5
 Built:        Fri Nov 20 17:56:04 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   a34a1d5
 Built:        Fri Nov 20 17:56:04 UTC 2015
 OS/Arch:      linux/amd64
$ docker pull busybox
Using default tag: latest
latest: Pulling from library/busybox

777c71afb634: Pull complete 
e940f619eabf: Pull complete 
Digest: sha256:af39243ae92c12504f260709da43f1b4bd17a802a86a367ffcd7f4913688d92a
Status: Downloaded newer image for busybox:latest
$ $(aws ecr get-login)                                                                        
WARNING: login credentials saved in /home/ec2-user/.docker/config.json
Login Succeeded
$ docker tag busybox [redacted].dkr.ecr.us-west-2.amazonaws.com/old:busybox
$ docker push [redacted].dkr.ecr.us-west-2.amazonaws.com/old:busybox
The push refers to a repository [[redacted].dkr.ecr.us-west-2.amazonaws.com/old] (len: 1)
e940f619eabf: Pushed 
777c71afb634: Pushed 
busybox: digest: sha256:a3651022ae45c15f5d7bc4164a7de8e9593edb634b546300316086314c7ae8c1 size: 2079
```
```
# Verify what we pushed

$ aws ecr describe-images --repo old
{
    "imageDetails": [
        {
            "registryId": "[redacted]",
            "repositoryName": "old",
            "imageDigest": "sha256:a3651022ae45c15f5d7bc4164a7de8e9593edb634b546300316086314c7ae8c1",
            "imageTags": [
                "busybox"
            ],
            "imageSizeInBytes": 741646,
            "imagePushedAt": 1608335345.0,
            "imageManifestMediaType": "application/vnd.docker.distribution.manifest.v1+prettyjws",
            "artifactMediaType": "application/vnd.docker.distribution.manifest.v1+prettyjws"
        }
    ]
}
$ aws ecr batch-get-image --repo old --image-ids imageDigest=sha256:a3651022ae45c15f5d7bc4164a7de8e9593edb634b546300316086314c7ae8c1 --query images[0].imageManifest --output text | jq .
{
  "schemaVersion": 1,
  "name": "old",
  "tag": "busybox",
  "architecture": "amd64",
  "fsLayers": [
    {
      "blobSum": "sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4"
    },
    {
      "blobSum": "sha256:d318a3354ec427748fe6cb8a4d97f7e99906596255fdd523e42c6c435fb4c975"
    }
  ],
  "history": [
    {
      "v1Compatibility": "{\"architecture\":\"amd64\",\"config\":{\"Hostname\":\"\",\"Domainname\":\"\",\"User\":\"\",\"AttachStdin\":false,\"AttachStdout\":false,\"AttachStderr\":false,\"Tty\":false,\"OpenStdin\":false,\"StdinOnce\":false,\"Env\":[\"PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin\"],\"Cmd\":[\"sh\"],\"Image\":\"sha256:b2c95316ee095165d5e02a2d3268b7b0c291d48a286d8b2c689dc4fea457319a\",\"Volumes\":null,\"WorkingDir\":\"\",\"Entrypoint\":null,\"OnBuild\":null,\"Labels\":null},\"container\":\"6caf2f12a00b51ceabd0ecb9d5da6a12721e70b018ca94156862976ed0701854\",\"container_config\":{\"Hostname\":\"6caf2f12a00b\",\"Domainname\":\"\",\"User\":\"\",\"AttachStdin\":false,\"AttachStdout\":false,\"AttachStderr\":false,\"Tty\":false,\"OpenStdin\":false,\"StdinOnce\":false,\"Env\":[\"PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin\"],\"Cmd\":[\"/bin/sh\",\"-c\",\"#(nop) \",\"CMD [\\\"sh\\\"]\"],\"Image\":\"sha256:b2c95316ee095165d5e02a2d3268b7b0c291d48a286d8b2c689dc4fea457319a\",\"Volumes\":null,\"WorkingDir\":\"\",\"Entrypoint\":null,\"OnBuild\":null,\"Labels\":{}},\"created\":\"2020-12-03T22:19:53.402932437Z\",\"docker_version\":\"19.03.12\",\"id\":\"2ff959721922567399c042fcaaf47ef46ba39c29272abdba85a6a5cab88fe7a8\",\"os\":\"linux\",\"parent\":\"86affc1fca7bc1d37f3d94ce67b7af6311bd7dde1d2f28ddd5c86b32cd505f6f\",\"throwaway\":true}"
    },
    {
      "v1Compatibility": "{\"id\":\"86affc1fca7bc1d37f3d94ce67b7af6311bd7dde1d2f28ddd5c86b32cd505f6f\",\"created\":\"2020-12-03T22:19:53.238498843Z\",\"container_config\":{\"Cmd\":[\"/bin/sh -c #(nop) ADD file:85e5bcb27fcc24f6a594d2e89493c4083ef596c2a73c5ccaa0a0255a48ba2cd0 in / \"]}}"
    }
  ],
  "signatures": [
    {
      "header": {
        "jwk": {
          "crv": "P-256",
          "kid": "ZLEV:T64R:ZVW3:NEXO:YGRI:SADR:SY5B:WWUX:2HWV:QS67:RUIR:WI7H",
          "kty": "EC",
          "x": "JwFQlUo4nfjhhOS19GlyqXXVqmSzu81hyEjaepJI3lM",
          "y": "3Yh_5peoWPqVjnSZRXKTe6htFKEa6DiLsGY_I06fljA"
        },
        "alg": "ES256"
      },
      "signature": "JC5zmyQ9UV_05LecRT6iLClgS9hlRwh9nQM4QOiCdMsNYW9wQqK9gyVw4Ap_7SjDhnMjoXEhM3e6jQbs2Waahw",
      "protected": "eyJmb3JtYXRMZW5ndGgiOjIwNzcsImZvcm1hdFRhaWwiOiJDbjAiLCJ0aW1lIjoiMjAyMC0xMi0xOFQyMzo0OTowNFoifQ"
    }
  ]
}
```
```
# Use it

$ kubectl run test --rm -it --image=[redacted].dkr.ecr.us-west-2.amazonaws.com/old:busybox
If you don't see a command prompt, try pressing enter.
/ # 
```
```
# Inspect it on the Bottlerocket node

$ sudo sheltie
bash-5.0# ctr -a /run/dockershim.sock -n k8s.io i ls | head -n2
REF                                                                                                                                      TYPE                                                      DIGEST                                                                  SIZE      PLATFORMS                                                                                LABELS                          
[redacted].dkr.ecr.us-west-2.amazonaws.com/old:busybox                                                                                 application/vnd.oci.image.manifest.v1+json                sha256:c6c678604ae22f33bb9aeba106b3019aeeb703dd199ea0395835669f2811c908 725.4 KiB linux/amd64                                                                              io.cri-containerd.image=managed 
```
</details>

**Comment by faarshad** [comment] 2021-01-07 22:34
@samuelkarp , after reading https://docs.aws.amazon.com/AmazonECR/latest/userguide/image-manifest-formats.html and testing with ECR, I am thinking that ECR is smart enough to detect that the client(containerd-1.3.7) does not support v2schema1 images and thus ECR translates them to a supported format when containerd pulls the image.

We are able to reproduce this issue with Artifactory registry but not with ECR on Bottlerocket-1.0.4. 

Given the fact that different registries are behaving differently in this aspect, I still think it is valuable to solve for generality and provide this configuration flag for allowing  v2schema1 images in Bottlerocket.

**Comment by samuelkarp** [comment] 2021-02-25 18:06
Hi @farshad-hobsons! My apologies for the lengthy delay in responding to you.

> I am thinking that ECR is smart enough to detect that the client(containerd-1.3.7) does not support v2schema1 images and thus ECR translates them to a supported format when containerd pulls the image.

The page https://docs.aws.amazon.com/AmazonECR/latest/userguide/image-manifest-formats.html describes the format conversions that ECR will perform.  The scenario I tested falls into the column labeled "Pushed to ECR as V2, schema 1" and "No translation available" for all of the rows.  I was able to validate that containerd is configured to support schema 1 and performs translation locally during the pull process.

> We are able to reproduce this issue with Artifactory registry but not with ECR on Bottlerocket-1.0.4.

Do you have an Artifactory registry that we can use for testing?  Alternately, are you able to test your Artifactory registry with cri-containerd outside of Bottlerocket and see if you have the same error?

In the meantime I'm going to retitle this issue to reflect that it's specific to Artifactory rather than a general issue with v2 schema 1 images.

**Comment by faarshad** [comment] 2021-02-26 19:32
@samuelkarp 
> Do you have an Artifactory registry that we can use for testing? 

Unfortunately, our Artifactory registry is tied to internal compliance restrictions. Btw, we have eliminated all the places where we had older docker clients pushing to artifactory registry, so this issue is not really a blocker for us.

> Alternately, are you able to test your Artifactory registry with cri-containerd outside of Bottlerocket and see if you have the same error?

Yes, i was able to reproduce outside of the Bottlerocket using the following steps:

1. Build an image on an older version of docker

`docker run --privileged --rm -it docker:1.9-dind /bin/sh`

```bash
# docker daemon
INFO[0000] API listen on /var/run/docker.sock
...

# cat Dockerfile
FROM alpine
CMD ["sh"]

# docker build -t alpine-artifactory-test .
Sending build context to Docker daemon 2.048 kB
Step 1 : FROM alpine
latest: Pulling from library/alpine
356f814854d6: Pull complete
f235c4538f64: Pull complete
Digest: sha256:2976d6110d5a33b859f538164ce634aae64c10f1e69346c14cb1ade9556b2f3b
Status: Downloaded newer image for alpine:latest
 ---> f235c4538f64
Step 2 : CMD sh
 ---> Running in 677cc3987963
 ---> 635f79ce570d
Removing intermediate container 677cc3987963
Successfully built 635f79ce570d
```

2. Push the image to Artifactory registry
```bash
# docker tag alpine-artifactory-test:latest REDACTED.jfrog.io/platform/alpine-artifactory-test:202102261300
# docker push REDACTED.jfrog.io/platform/alpine-artifactory-test:202102261300
```

3. Validate in Artifactory that manifest.json shows `"schemaVersion": 1,` for the image `REDACTED.jfrog.io/platform/alpine-artifactory-test:202102261300`
```json
{
   "schemaVersion": 1,
   "name": "platform/alpine-artifactory-test",
   "tag": "202102261300",
   "architecture": "amd64",
   "fsLayers": [
      {
         "blobSum": "sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4"
      },
      {
         "blobSum": "sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4"
      },
      {
         "blobSum": "sha256:ad179b0cf9c37de36bd5f29af110b74f909aa36b93c897300f14aced4729104b"
      }
   ],
   "history": [
      {
         "v1Compatibility": "{\"id\":\"635f79ce570de21db3d89ff52375a5b6ee7b12d8037319c999a157dac4c09745\",\"parent\":\"2968c33ee8345dd31a30bf062959ca820a2616c63c04078d16c852fa82f150e9\",\"created\":\"2021-02-26T18:28:12.2356635Z\",\"container\":\"677cc39879636d3d9a40f06eccbb0125e50932ed2258f83bc96a6e694efe8859\",\"container_config\":{\"Hostname\":\"677cc3987963\",\"Domainname\":\"\",\"User\":\"\",\"AttachStdin\":false,\"AttachStdout\":false,\"AttachStderr\":false,\"Tty\":false,\"OpenStdin\":false,\"StdinOnce\":false,\"Env\":[\"PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin\"],\"Cmd\":[\"/bin/sh\",\"-c\",\"#(nop) CMD [\\\"sh\\\"]\"],\"Image\":\"f235c4538f6479646763c1c18e224f536795e2cba38234d471ccd1bda5bd3a0c\",\"Volumes\":null,\"WorkingDir\":\"\",\"Entrypoint\":null,\"OnBuild\":[],\"Labels\":{}},\"docker_version\":\"1.9.1\",\"config\":{\"Hostname\":\"677cc3987963\",\"Domainname\":\"\",\"User\":\"\",\"AttachStdin\":false,\"AttachStdout\":false,\"AttachStderr\":false,\"Tty\":false,\"OpenStdin\":false,\"StdinOnce\":false,\"Env\":[\"PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin\"],\"Cmd\":[\"sh\"],\"Image\":\"f235c4538f6479646763c1c18e224f536795e2cba38234d471ccd1bda5bd3a0c\",\"Volumes\":null,\"WorkingDir\":\"\",\"Entrypoint\":null,\"OnBuild\":[],\"Labels\":{}},\"architecture\":\"amd64\",\"os\":\"linux\"}"
      },
      {
         "v1Compatibility": "{\"architecture\":\"amd64\",\"config\":{\"Hostname\":\"\",\"Domainname\":\"\",\"User\":\"\",\"AttachStdin\":false,\"AttachStdout\":false,\"AttachStderr\":false,\"Tty\":false,\"OpenStdin\":false,\"StdinOnce\":false,\"Env\":[\"PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin\"],\"Cmd\":[\"/bin/sh\"],\"Image\":\"sha256:e61ba58591fdf59d4950dccd6f7af139bfbf8919ac33c613585c20799ab8f93e\",\"Volumes\":null,\"WorkingDir\":\"\",\"Entrypoint\":null,\"OnBuild\":null,\"Labels\":null},\"container\":\"ca4ad1a638ed081e56996a1dad0454d2e49f0309848ddfcf9d91373875606eb3\",\"container_config\":{\"Hostname\":\"ca4ad1a638ed\",\"Domainname\":\"\",\"User\":\"\",\"AttachStdin\":false,\"AttachStdout\":false,\"AttachStderr\":false,\"Tty\":false,\"OpenStdin\":false,\"StdinOnce\":false,\"Env\":[\"PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin\"],\"Cmd\":[\"/bin/sh\",\"-c\",\"#(nop) \",\"CMD [\\\"/bin/sh\\\"]\"],\"Image\":\"sha256:e61ba58591fdf59d4950dccd6f7af139bfbf8919ac33c613585c20799ab8f93e\",\"Volumes\":null,\"WorkingDir\":\"\",\"Entrypoint\":null,\"OnBuild\":null,\"Labels\":{}},\"created\":\"2021-02-17T21:19:54.811094842Z\",\"docker_version\":\"19.03.12\",\"id\":\"2968c33ee8345dd31a30bf062959ca820a2616c63c04078d16c852fa82f150e9\",\"os\":\"linux\",\"parent\":\"2aa7ee4964945ea0ef517c539a3261386ae779812871be9699ab76d5c7581c79\",\"throwaway\":true}"
      },
      {
         "v1Compatibility": "{\"id\":\"2aa7ee4964945ea0ef517c539a3261386ae779812871be9699ab76d5c7581c79\",\"created\":\"2021-02-17T21:19:54.634967707Z\",\"container_config\":{\"Cmd\":[\"/bin/sh -c #(nop) ADD file:80bf8bd014071345b1c0364eeb0a5e48f3fb0d87f9c31cb990e57caa652b59b8 in / \"]}}"
      }
   ],
   "signatures": [
      {
         "header": {
            "jwk": {
               "crv": "P-256",
               "kid": "ATSH:CUQA:5GZ2:FCXL:RYST:C63K:TH6T:HFBR:FRB5:I6TO:OB3X:LJJM",
               "kty": "EC",
               "x": "f5VhJKrAoMTVpUORduU_ecGVwgflvhdo8AN-foALFrk",
               "y": "YwVhgaZhQroE1nK8nBluMgyyL1_SyrWCk4j6vPlYJUo"
            },
            "alg": "ES256"
         },
         "signature": "kyzGaYQlFjn2PEOYYhgSxJZxRP9FLcIoNuv6e0y95Uew6JeUpw8zW-7o-TIupdQo9ekPq-IHWlius6N3jnkwbg",
         "protected": "eyJmb3JtYXRMZW5ndGgiOjM2MTAsImZvcm1hdFRhaWwiOiJDbjAiLCJ0aW1lIjoiMjAyMS0wMi0yNlQxODozNDo1N1oifQ"
      }
   ]
}
```

4. Pull the `REDACTED.jfrog.io/platform/alpine-artifactory-test:202102261300` image with ctr-1.3.7 on your local:
```bash
# docker run -it --rm --user root  amazonlinux:2 /bin/bash
# yum install libseccomp-devel.x86_64 procps wget tar tmux -y
# wget https://github.com/containerd/containerd/releases/download/v1.3.7/containerd-1.3.7-linux-amd64.tar.gz && tar zxf containerd-1.3.7-linux-amd64.tar.gz && cp -r bin/* /usr/local/bin/
# containerd &

# export KEY="REDACTED_USER:REDACTED_PASS"

# date && ctr --debug image pull --user $KEY REDACTED.jfrog.io/platform/alpine-artifactory-test:202102261300
Fri Feb 26 18:58:54 UTC 2021
DEBU[0000] fetching                                      image="REDACTED.jfrog.io/platform/alpine-artifactory-test:202102261300"
DEBU[0000] resolving                                     host=REDACTED.jfrog.io
DEBU[0000] do request                                    host=REDACTED.jfrog.io request.header.accept="application/vnd.docker.distribution.manifest.v2+json, application/vnd.docker.distribution.manifest.list.v2+json, application/vnd.oci.image.manifest.v1+json, application/vnd.oci.image.index.v1+json, */*" request.header.user-agent=containerd/v1.3.7 request.method=HEAD url="https://REDACTED.jfrog.io/v2/platform/alpine-artifactory-test/manifests/202102261300"
DEBU[0000] fetch response received                       host=REDACTED.jfrog.io response.header.connection=keep-alive response.header.content-type="application/json;charset=ISO-8859-1" response.header.date="Fri, 26 Feb 2021 18:58:55 GMT" response.header.docker-distribution-api-version=registry/2.0 response.header.strict-transport-security="max-age=15724800; includeSubDomains" response.header.www-authenticate="Bearer realm=\"https://REDACTED.jfrog.io/artifactory/api/docker/platform-docker-sandbox/v2/token\",service=\"REDACTED.jfrog.io\",scope=\"repository:platform/alpine-artifactory-test:pull\"" response.header.x-artifactory-id=ec988e49ac15f571892d547f6a965c604bbe413e response.header.x-artifactory-node-id=REDACTED-artifactory-primary-1 response.header.x-jfrog-version="Artifactory/7.12.3 71203900" response.status="401 Unauthorized" url="https://REDACTED.jfrog.io/v2/platform/alpine-artifactory-test/manifests/202102261300"
DEBU[0000] Unauthorized                                  header="Bearer realm=\"https://REDACTED.jfrog.io/artifactory/api/docker/platform-docker-sandbox/v2/token\",service=\"REDACTED.jfrog.io\",scope=\"repository:platform/alpine-artifactory-test:pull\"" host=REDACTED.jfrog.io
DEBU[0000] do request                                    host=REDACTED.jfrog.io request.header.accept="application/vnd.docker.distribution.manifest.v2+json, application/vnd.docker.distribution.manifest.list.v2+json, application/vnd.oci.image.manifest.v1+json, application/vnd.oci.image.index.v1+json, */*" request.header.user-agent=containerd/v1.3.7 request.method=HEAD url="https://REDACTED.jfrog.io/v2/platform/alpine-artifactory-test/manifests/202102261300"
DEBU[0000] fetch response received                       host=REDACTED.jfrog.io response.header.accept-ranges=bytes response.header.cache-control=no-store response.header.connection=keep-alive response.header.content-disposition="attachment; filename=\"manifest.json\"" response.header.content-length=4257 response.header.content-type=application/vnd.docker.distribution.manifest.v1+prettyjws response.header.date="Fri, 26 Feb 2021 18:58:55 GMT" response.header.docker-content-digest="sha256:47f3a7cbe99624046acd562830770aa34f29772f7acf85e77006edc7823dc993" response.header.docker-distribution-api-version=registry/2.0 response.header.etag=b14a96af52ef59640d90b4f486edba2102b83fdd response.header.last-modified="Fri, 26 Feb 2021 18:34:58 GMT" response.header.strict-transport-security="max-age=15724800; includeSubDomains" response.header.x-artifactory-filename=manifest.json response.header.x-artifactory-id=ec988e49ac15f571892d547f6a965c604bbe413e response.header.x-artifactory-node-id=REDACTED-artifactory-primary-1 response.header.x-checksum-md5=8468aee005f1ef2bcca5d4e9c2af10ac response.header.x-checksum-sha1=b14a96af52ef59640d90b4f486edba2102b83fdd response.header.x-checksum-sha256=a8ea6ee2a0c04cf0aee9ca5c45f850c0b0a3f6c43c28b71a1edb49e69e216bec response.header.x-jfrog-version="Artifactory/7.12.3 71203900" response.header.x-request-id=8b7a93b4cadd63c2f76d9292e6f00609 response.status="200 OK" url="https://REDACTED.jfrog.io/v2/platform/alpine-artifactory-test/manifests/202102261300"
DEBU[0000] resolved                                      desc.digest="sha256:47f3a7cbe99624046acd562830770aa34f29772f7acf85e77006edc7823dc993" host=REDACTED.jfrog.io
DEBU[0000] fetch schema 1
DEBU[0000] do request                                    digest="sha256:47f3a7cbe99624046acd562830770aa34f29772f7acf85e77006edc7823dc993" request.header.accept="application/vnd.docker.distribution.manifest.v1+prettyjws, */*" request.header.user-agent=containerd/v1.3.7 request.method=GET url="https://REDACTED.jfrog.io/v2/platform/alpine-artifactory-test/manifests/sha256:47f3a7cbe99624046acd562830770aa34f29772f7acf85e77006edc7823dc993"
DEBU[0001] fetch response received                       digest="sha256:47f3a7cbe99624046acd562830770aa34f29772f7acf85e77006edc7823dc993" response.header.connection=keep-alive response.header.content-type=application/json response.header.date="Fri, 26 Feb 2021 18:58:56 GMT" response.header.docker-distribution-api-version=registry/2.0 response.header.strict-transport-security="max-age=15724800; includeSubDomains" response.header.x-artifactory-id=5797809d26722f9a7ea15b58488837e71be35aa1 response.header.x-artifactory-node-id=REDACTED-artifactory-primary-2 response.header.x-jfrog-version="Artifactory/7.12.3 71203900" response.status="404 Not Found" url="https://REDACTED.jfrog.io/v2/platform/alpine-artifactory-test/manifests/sha256:47f3a7cbe99624046acd562830770aa34f29772f7acf85e77006edc7823dc993"
ctr: httpReaderSeeker: failed open: content at https://REDACTED.jfrog.io/v2/platform/alpine-artifactory-test/manifests/sha256:47f3a7cbe99624046acd562830770aa34f29772f7acf85e77006edc7823dc993 not found: not found
```

**Comment by samuelkarp** [comment] 2021-03-01 18:22
> Yes, i was able to reproduce outside of the Bottlerocket using the following steps

Is this something that you can report either upstream to the [containerd project](https://github.com/containerd/containerd) or to JFrog about their Artifactory product?  Unfortunately without a way to replicate the failure there's not much that I can do to debug.

> Btw, we have eliminated all the places where we had older docker clients pushing to artifactory registry, so this issue is not really a blocker for us.

I'm glad to hear this!  Please let us know if you have any other blockers in the future.

**Comment by etungsten** [comment] 2022-03-22 20:15
Closing issue as it seems the issue resides in containerd and not bottlerocket specifically. And the issue is no longer a blocker. Please feel free to re-open the issue if that's not the case.

**Closed as completed by etungsten** 2022-03-22 20:15 UTC
Labels: type/bug
