### ISSUE TITLE
BottleRocket sometimes fails to start on Ec2 instances

### ISSUE THREAD

**Issue by avivmag** [bottlerocket-os/bottlerocket#2980] opened 2023-04-05 17:14 UTC
Hello,

I am using aws cdk to deploy an ECS cluster.
I am not familiar at all with BottleRocket, I just use it as an image for the EC2 instances that are part of a ASG that is in the cluster.
Sometimes the deploy is successful, sometimes not (sounds like some race condition).
I am using a1.medium machines in this cluster.

Not sure how much it helps but here is a gist of the code I am using to deploy that environment (C#):

[bottlerocket_cdk.txt](https://github.com/bottlerocket-os/bottlerocket/files/11161454/bottlerocket_cdk.txt)

To try and debug the issue I've connected to the system log of one of the ec2 instances.
This is the output when the deploy is unsuccessful:

[bottlerocket_ec2_output.txt](https://github.com/bottlerocket-os/bottlerocket/files/11161435/bottlerocket_ec2_output.txt)

Hope it helps,
Please let me know if there are more stuff I can do to shed some light over this issue.
Thank you.

**Comment by ecpullen** [comment] 2023-04-05 17:47
Thanks for reaching out @avivmag.

We are taking a look at the logs and will try to reproduce the error on our end. It appears the `a1.medium` is an older instance. Have you seen the same error with other instance types?

**Comment by avivmag** [comment] 2023-04-05 20:22
Hi @ecpullen,
Thank you for your response!

I've deployed it many times with this type of instances and it used to work.
I am not deploying that architecture on an everyday basis, but I believe that this issue did not exist a week or two ago.
I'll try to deploy the same architecture with m7g.large instead, and post an update when It will reach the stage of that error (should take about 20-30 minutes).

**Comment by avivmag** [comment] 2023-04-05 20:50
Tried it and it might have worked 🤔 
I've created two clusters,
One of them with one instance of a1.medium type while the other with four instances of m7g.large type.
The first gave an equivalent output to the one with the error:

[bottlerocket_cdk_a1_medium.txt](https://github.com/bottlerocket-os/bottlerocket/files/11162916/bottlerocket_cdk_a1_medium.txt)

The second did not return this type of error (although returned other errors, but I guess that they can be ignored):

[bottlerocket_m7g_large.txt](https://github.com/bottlerocket-os/bottlerocket/files/11162928/bottlerocket_m7g_large.txt)

There is an issue with it though.
Seems like ECS won't consider those instances as usable for some reason,
Not sure about it, but my guess is that it has nothing to do with BottleRocket.

Does that means that instances of a1 types should not be used with BottleRocket?

**Comment by ecpullen** [comment] 2023-04-05 21:58
Thanks for the quick update @avivmag. I will take a look at the new logs.

**Comment by ecpullen** [comment] 2023-04-05 22:03
Based on the logs it looks like there may be an issue with the userdata used to launch the bottlerocket nodes. Are you using custom userdata, or are you letting the CDK handle userdata creation?

**Comment by avivmag** [comment] 2023-04-06 08:27
Thank you for your quick replies as well!

I am not using any custom data on that cluster.
I went to check exactly what CDK does with it, and I found [this](https://github.com/aws/aws-cdk/blob/cea1039e3664fdfa89c6f00cdaeb1a0185a12678/packages/%40aws-cdk/aws-ecs/lib/cluster.ts#L397).
Now that I think of it, I've made an update to CDK itself.
I'll try to set the versions back and post an update about it.
It should take 20-30 minutes.

**Comment by avivmag** [comment] 2023-04-06 09:18
Same outcome,
On that occasion 4 out of 5 of instances of type a1.medium failed to deploy.
Btw here is a system log for a successful load:

[bottlerocket_cdk_successful_load.txt](https://github.com/bottlerocket-os/bottlerocket/files/11168413/bottlerocket_cdk_successful_load.txt)

Please let me know if there is anything more I can do to help,
Thanks again for your help @ecpullen!

**Comment by ecpullen** [comment] 2023-04-07 17:33
Hi @avivmag I was able to launch several Bottlerocket nodes using a cdk stack build from your gist. I have now been able to reproduce the bug. 

<details>
<summary>
CDK Stack
</summary>

```
using Constructs;
using Amazon.CDK;
using Amazon.CDK.AWS.ECS;
using Amazon.CDK.AWS.EC2;
using Amazon.CDK.AWS.AutoScaling;
using Amazon.CDK.AWS.SNS;

namespaceTest
{
    public class TestStack : Stack
    {
        internal TestStack(Construct scope, string id, IStackProps props = null) : base(scope, id, props)
        {
            var vpc = new Vpc(this, "MyVpc", new VpcProps
            {
                MaxAzs = 3 // Default is all AZs in region
            });

            var cluster = new TestCluster(this, "MyCluster", vpc);
        }
    }

    public class TestCluster : Cluster
    {
        internal TestCluster(
            Construct scope,
            string id,
            IVpc vpc) : base(scope, id, new ClusterProps
            {
                Vpc = vpc,
            })
        {
            var autoScalingGroup = new AutoScalingGroup(this, "test-asg", new AutoScalingGroupProps
            {
                MinCapacity = 4,
                MaxCapacity = 30,
                InstanceMonitoring = Monitoring.BASIC,
                GroupMetrics = new GroupMetrics[]{
                                GroupMetrics.All(),
                            },
                AssociatePublicIpAddress = false,
                MachineImage = new BottleRocketImage(new BottleRocketImageProps
                {
                    Architecture = InstanceArchitecture.ARM_64,
                }),
                InstanceType = InstanceType.Of(InstanceClass.ARM1, InstanceSize.MEDIUM),
                Vpc = vpc,
            });
            autoScalingGroup.ScaleToTrackMetric("test-scale-on-memory", new MetricTargetTrackingProps
            {
                Metric = MetricMemoryUtilization(),
                TargetValue = 75,
            });
            AddAsgCapacityProvider(
                new AsgCapacityProvider(
                    this,
                    "test-asg-capacity",
                    new AsgCapacityProviderProps
                    {
                        AutoScalingGroup = autoScalingGroup,
                        CanContainersAccessInstanceRole = true,
                        MachineImageType = MachineImageType.BOTTLEROCKET,
                        EnableManagedTerminationProtection = false,
                    })
            );
        }
    }
}
```

</details>

**Comment by ecpullen** [comment] 2023-04-07 23:00
Hi @avivmag,
It seems that this issue is specific to variants that use the 5.10 kernel on arm64 instance types with a single vCPU. Changing the instance type to a1.large solved the problem in my CDK stack.

**Comment by avivmag** [comment] 2023-04-08 13:23
Interesting 🤔,
It used to work a while ago,
So I just made a test with an older version of bottlerocket.
I used AWS Management Console for it (not anything to do with CDK). 
I've created two ASGs, both with instance type of a1.medium, both have 4 instances running.

One with the newest version of bottlerocket (1.13.2) - ami-028925c6badbc01d2,
and one with an older one (1.12.0) - ami-0e6edf654457a1020.
The newest one failed - 3/4 failed to load.
The older one seemed to load successfully mostly - 4/4 loaded successfully (health check succeeded) but with the following error:
`[   66.851890] host-ctr[466]: time="2023-04-08T12:24:51Z" level=error msg="retries exhausted: failed to resolve reference \"ecr.aws/arn:aws:ecr:us-east-1:328549459982:repository/bottlerocket-control:v0.7.0\": NoCredentialProviders: no valid providers in chain. Deprecated.\n\tFor verbose messaging see aws.Config.CredentialsChainVerboseErrors" ref="ecr.aws/arn:aws:ecr:us-east-1:328549459982:repository/bottlerocket-control:v0.7.0"`

Not 100% sure if it means that the status of it is considered to be OK but it did load and the health check of all 4 were successful.
Might it be that some change in the newest version of bottlerocket is giving that error?

**Comment by etungsten** [comment] 2023-04-09 04:28
Hi @avivmag,

Your assessment is correct. This is a new regression that cropped up with the addition of https://github.com/bottlerocket-os/bottlerocket/pull/2807/commits/6a370b6e62feb827062acd57ed1fddd1d4396e3b and https://github.com/bottlerocket-os/bottlerocket/pull/2935/commits/4f81e2759cbe28673b829c46aeadd9e0cf3f313e in the 1.13.x versions of Bottlerocket. Though the impact seems to be limited to variants running on the 5.10 kernel and small 1vCPU instance types. I'm currently in progress of testing a fix for this issue and hope to address this soon. Thanks for bringing this to our attention!

**Comment by avivmag** [comment] 2023-04-09 15:47
Hi @etungsten,

Thank you for your reply and for the time that you put into this issue.
I just want to share my perspective on why I feel this is somewhat an important matter for the Bottlerocket project.

The initial reason for me to use a1.medium was that it is [the most cost-effective](https://instances.vantage.sh/?selected=a1.medium) instance type that [supports ENI trunking](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/container-instance-eni.html).
So as for a testing environment, it is probably used quite often by engineers who are new to AWS or specifically to ECS and tries Bottlerocket for the first time.

**Closed as completed** 2023-04-11 19:31 UTC
Labels: type/bug, status/in-progress
