### ISSUE TITLE
Bottlerocket Node group AMI doesn't updates to latest

### ISSUE THREAD

**Issue by cloudkarthik99** [bottlerocket-os/bottlerocket#3247] opened 2023-07-05 09:22 UTC
**Image I'm using:**
Bottlerocket OS 1.13.4 (aws-k8s-1.23)
eksctl version=0.141.0

**What I expected to happen:**
EKS nodegroup to be updated with the latest Bottlerocket AMI release version(1.14) for the same K8s version

**What actually happened:**
No update happening until we change the nodegroup name or change the K8s version manually.

**How to reproduce the problem:**

The `eksctl` cluster config:
```
 cluster_config = <<CLUSTERCONFIG
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: ${local.ressources_name}
  region: ${local.region}
  tags: ${jsonencode(local.common_tags)}
  version: "${var.eks_version}" #1.23

vpc:
  subnets:
    private:
  %{for item in data.aws_subnet.vpc_subnets~}
    ${item.availability_zone}: { id: ${item.id} }
  %{endfor~}

managedNodeGroups:
  - name: ${var.eks_nodegroup_name}
    labels: { 
      role: workers,
      project: ${lower(var.tag_project)},
      application: ${replace(lower(var.tag_application), " ", "_")},
      environment: ${local.environment}, 
      classification: ${lower(local.classification)}, # TEST or PROD
      region: ${lower(local.region)},
      k8s_dns_name: ${local.k8s_dns_name},}
    }
    instanceType: ${var.eks_instance_type}     #t3.xlarge
    minSize: ${var.eks_min_size}
    maxSize: ${var.eks_max_size}
    desiredCapacity: ${var.eks_desired_capacity}
    updateConfig:
      # https://eksctl.io/usage/eks-managed-nodes/#handling-parallel-upgrades-for-nodes
      maxUnavailablePercentage: 50
    amiFamily: ${var.ami_family}  # Bottlerocket or AmazonLinux2
    privateNetworking: true
    tags: ${jsonencode(local.common_tags)}
    iam:
      withAddonPolicies:
        autoScaler: true
        externalDNS: true
        certManager: true
        cloudWatch: true
        imageBuilder: true

cloudWatch:
  clusterLogging:
    enableTypes: ["audit", "authenticator"]

addons:
- name: aws-ebs-csi-driver
  
  CLUSTERCONFIG
}
```

We have Private EKS clusters created in separate AWS accounts from the same Repository and same cluster config containing AmazonLinux2 AMI in one account EKS cluster and bottlerocket in the other account EKS cluster.

Everytime we run the CI/CD pipeline, the cloudformation stack checks for the latest AL2 AMI version if present and updates the EKS node group  (when and only we run the pipeline not auto updates)

But this is not the same case for Bottlerocket nodes for the cloudformation stack to check for the latest bottlerocket AMI release version and update it until and unless we make the cluster config changes like Nodegroup name change or K8s version upgrade (1.23 to 1.24).

Even though when I am able to create a bottlerocket nodegroup with the latest AMI version (1.14),
but update from 1.13 AMI version to 1.14 AMI version for the same K8s version is not seem to be the case.

When I checked to compare difference between the cloudformation template of Bottlerocket EKS cluster and AL2 EKS cluster, 
I could see the `ReleaseVersion` parameter being present in the AL2 cloudformation template which I couldn't see as ofcourse `ReleaseVersion` parameter is not supported in Bottlerocket.

 But I didnt mention the `ReleaseVersion` parameter anywhere in Clusterconfig and I suspect this is the reason for the CNF to check for latest AMI and update the nodegroup.

I could see from AWS console for the update available as below though:
![image](https://github.com/bottlerocket-os/bottlerocket/assets/105298024/2bb45e5c-ff13-481b-a3f7-df305fce373b)
![image](https://github.com/bottlerocket-os/bottlerocket/assets/105298024/a14e768d-e4b6-494c-be6b-0b22861cb14f)

**Comment by etungsten** [comment] 2023-07-05 18:13
Hi @remo1435,

Thanks for reaching out. I checked with a few folks and confirmed that you should able to specify the `ReleaseVersion` parameter in the `EKS::Nodegroup` CloudFormation resource for the Bottlerocket version. So this might be an issue to open with `eksctl` so their generated CFN template includes that field for Bottlerocket. You can also try adding the field manually and see if that works.

In the meantime, you can also try using the [Bottlerocket Update Operator](https://github.com/bottlerocket-os/bottlerocket-update-operator/tree/v1.1.0) for automatic OS updates across your Bottlerocket nodes.

Since this issue doesn't isn't with the OS itself but rather with other tooling, I'm gonna go ahead and close this issue.

**Closed as completed** 2023-07-05 18:16 UTC
Labels: status/needs-triage
