### ISSUE TITLE
Expose Kubernetes maxParallelImagePulls

### ISSUE THREAD

**Issue by JacobHenner** [bottlerocket-os/bottlerocket#4176] opened 2024-09-04 12:23 UTC
**What I'd like:**

The [kubelet setting](https://kubernetes.io/docs/reference/config-api/kubelet-config.v1beta1/#kubelet-config-k8s-io-v1beta1-KubeletConfiguration) `maxParallelImagePulls` is not exposed through [Bottlerocket's settings](https://bottlerocket.dev/en/os/1.20.x/api/settings/) interface. It'd be helpful if we could set this value, as we'd like to limit parallel image pulls in certain situations.

**Any alternatives you've considered:**

We could build a custom Bottlerocket-derived AMI with this configuration baked in, but that complicates management of our clusters and would require us to maintain variant AMIs.

**Comment by yeazelm** [comment] 2024-09-04 16:24
Hello @JacobHenner, thanks for cutting this issue, I think this is the same request as https://github.com/bottlerocket-os/bottlerocket/issues/4058 right?

**Comment by JacobHenner** [comment] 2024-09-04 16:28
> Hello @JacobHenner, thanks for cutting this issue, I think this is the same request as https://github.com/bottlerocket-os/bottlerocket/issues/4058 right?

No - that request is about allowing parallel image pulls (they're already allowed by default). This request is about making the parallelism configurable.

**Comment by yeazelm** [comment] 2024-09-04 16:36
We intend to to both enabling and configuration of `maxParallelImagePulls` in https://github.com/bottlerocket-os/bottlerocket/issues/4058. I'll close this issue and add a comment clarifying that we will do both as part of #4058.

**Comment by yeazelm** [comment] 2024-09-04 16:38
Closing as duplicate of #4058

**Closed as not planned by yeazelm** 2024-09-04 16:38 UTC
Labels: type/enhancement, status/needs-triage
