### ISSUE TITLE
How to install additional softwares in the Bottlerocket instance ?

### ISSUE THREAD

**Issue by jackie-JD** [bottlerocket-os/bottlerocket#1222] opened 2020-11-21 06:15 UTC
**What I'd like:**
1. 
Currently, I refer to the portal https://github.com/bottlerocket-os/bottlerocket/blob/develop/QUICKSTART-EKS.md to create one my own cluster, and the cluster is based on bottlerocket os.
2. I have the following questions:
(1) I use "kubectl get nodes" command to get the bottlerocket nodes and I login to the bottlerocket, found that the filesystem is read-only except /tmp folder. My question is: Do I just use the /tmp folder when I want to write my data to the nodes ?
(2) For my case, if I need to install some special tools for some purpose, Can I install these tools in the bottlerocket OS? If so, how do I do that ？ 

Hope to get the response from you.
Thank you

**Any alternatives you've considered:**

**Comment by caoruidong** [comment] 2020-11-21 14:31
1) You cannot write your data to nodes, all worload are containers
2) You can create your own bottlerocket image with these packages

**Comment by jackie-JD** [comment] 2020-11-22 01:41
Thank you, Frank

1. You mentioned that I can create my own bottlerocket image, what does this mean ? And how can I do it ? 
Do you have documents for it ?

2. 
For storaging my data permanently, if I use the aws EFS CSI like the following style:
spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: linux
        image: amazonlinux:2 
        command: ["/bin/sh"]
        args: ["-c", "while true; do echo $(date -u) >> /efs-data/out.txt; sleep 5; done"]
        volumeMounts:
        - name: efs-storage
          mountPath: /efs-data
      volumes:
      - name: efs-storage
        persistentVolumeClaim:
          claimName: efs-claim

my question is : I know that the data is in the /efs-data in containers. BUT where are the mapping folders in the docker host(bottlerocket system) ? or How I can access them ?

**Comment by caoruidong** [comment] 2020-11-22 14:58
See https://github.com/bottlerocket-os/bottlerocket/blob/develop/BUILDING.md. I'm just a fan, not official. I guess the folders in the host is probably /var/kubernetes/pods/.../volumes/..., just like other kubernetes clusters.

**Comment by jackie-JD** [comment] 2020-11-22 15:04
Thanks Frank

Do you mind to add you as a friend using QQ or WeChat ?

**Comment by webern** [comment] 2020-11-22 18:13
@jackie-JD, thank you for trying out Bottlerocket. @caoruidong is correct that the intended use-case for Bottlerocket is to run containers, currently via EKS or ECS. As such, the software you want to run is in the container image that you run on Bottlerocket.

For breakglass debugging, you can use the Admin container, where yum is available. When you install software in the admin container, you do so in the context of the container, not on the host.

As for the mount points for EFS volumes, I can check on that for you, but I think it would help if you provided a higher level description of what you are trying to do. For most use cases we wouldn't expect a need to inspect EFS mount points on the host.

What is it that you need to add to Bottlerocket, and how will it be used?

Thanks!

**Comment by caoruidong** [comment] 2020-11-23 02:59
> Thanks Frank
> 
> Do you mind to add you as a friend using QQ or WeChat ?

 OK. My wechat ID is crdfrank

**Comment by jackie-JD** [comment] 2020-11-23 15:04
@caoruidong, I unable to fins the id crdfrank from the wechat client and my id is wxid_ghha1y0bvk6922. Could you add me from your side ?  Thank you.

**Comment by jackie-JD** [comment] 2020-11-23 15:16
@webern Thanks for your replying.
We have one application and we build it into the docker image style. 
Currently, we deploy the docker container to one EKS cluster which based on the Amazon Linux 2 OS. And for the storage we use the efs system. It can works well.
Since the bottlerocket comes, we plan to move the application from the Amazon Linux 2 to the Bottlerocket, I am trying to deploy the application to the bottlerocket and still want to use the efs csi. 
But when I try to install the EFS CSI driver, meet some erros causing driver is not installed successfully.
The details logs are as follows:
C:\work\iso\CIS\docker\cch-dma\aws-efs-csi-driver\examples\kubernetes\multiple_pods>C:\work\iso\CIS\docker\kubectl.exe get pods
NAME                                                       READY   STATUS              RESTARTS   AGE
app1                                                       0/1     ContainerCreating   0          17s
app2                                                       0/1     ContainerCreating   0          17s
cis-deployment-5b9555566b-8l8fx                            1/1     Running             300        2d7h
nginx-app                                                  1/1     Running             0          5d6h
nginx-app1                                                 1/1     Running             0          4d7h
nginx-ingress-1605678928-controller-75c5b84478-7b5cl       1/1     Running             0          4d5h
nginx-ingress-1605678928-default-backend-cbf5c76b7-wlf6m   1/1     Running             0          4d5h

C:\work\iso\CIS\docker\cch-dma\aws-efs-csi-driver\examples\kubernetes\multiple_pods>C:\work\iso\CIS\docker\kubectl.exe describe pods app1
Name:         app1
Namespace:    default
Priority:     0
Node:         ip-192-168-31-184.ec2.internal/192.168.31.184
Start Time:   Sun, 22 Nov 2020 19:34:31 +0800
Labels:       <none>
Annotations:  kubernetes.io/psp: eks.privileged
Status:       Pending
IP:
IPs:          <none>
Containers:
  app1:
    Container ID:
    Image:         busybox
    Image ID:
    Port:          <none>
    Host Port:     <none>
    Command:
      /bin/sh
    Args:
      -c
      while true; do echo $(date -u) >> /data/out1.txt; sleep 5; done
    State:          Waiting
      Reason:       ContainerCreating
    Ready:          False
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /data from persistent-storage (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-hw965 (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  persistent-storage:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  efs-claim
    ReadOnly:   false
  default-token-hw965:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-hw965
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason            Age               From                                     Message
  ----     ------            ----              ----                                     -------
  Warning  FailedScheduling  48s               default-scheduler                        error while running "VolumeBinding" filter plugin for pod "app1": pod has unbound immediate PersistentVolumeClaims
  Warning  FailedScheduling  47s               default-scheduler                        error while running "VolumeBinding" filter plugin for pod "app1": pod has unbound immediate PersistentVolumeClaims
  Normal   Scheduled         40s               default-scheduler                        Successfully assigned default/app1 to ip-192-168-31-184.ec2.internal
  Warning  FailedMount       9s (x7 over 40s)  kubelet, ip-192-168-31-184.ec2.internal  MountVolume.MountDevice failed for volume "efs-pv" : kubernetes.io/csi: attacher.MountDevice failed to create newCsiDriverClient: driver name efs.csi.aws.com not found in the list of registered CSI drivers

C:\work\iso\CIS\docker>kubectl get pods -n kube-system  -o wide | findstr efs
efs-csi-node-2scq5                   2/3     CrashLoopBackOff   4          111s   192.168.54.201   ip-192-168-54-201.ec2.internal   <none>           <none>
efs-csi-node-8gvxs                   2/3     CrashLoopBackOff   5          111s   192.168.31.184   ip-192-168-31-184.ec2.internal   <none>           <none>
efs-csi-node-q49r8                   2/3     CrashLoopBackOff   4          111s   192.168.44.14    ip-192-168-44-14.ec2.internal    <none>           <none>
efs-csi-node-s47qb                   2/3     CrashLoopBackOff   4          111s   192.168.7.36     ip-192-168-7-36.ec2.internal     <none>           <none>


C:\work\iso\CIS\docker>kubectl -n kube-system logs -f efs-csi-node-s47qb  -c efs-plugin
I1122 12:24:48.566895       1 mount_linux.go:163] Cannot run systemd-run, assuming non-systemd OS
I1122 12:24:48.566971       1 mount_linux.go:164] systemd-run failed with: exit status 1
I1122 12:24:48.566980       1 mount_linux.go:165] systemd-run output:
I1122 12:24:48.567099       1 driver.go:87] Starting watchdog
I1122 12:24:48.567164       1 efs_watch_dog.go:174] Copying /etc/amazon/efs/efs-utils.conf since it doesn't exist
F1122 12:24:48.567205       1 main.go:50] open /etc/amazon/efs/efs-utils.conf: permission denied

**Comment by webern** [comment] 2020-11-23 21:38
I tried reproducing the issue and found an avc denial. `Nov 23 21:12:27 ip-192-168-9-184.us-west-2.compute.internal kernel: audit: type=1400 audit(1606165947.053:6): avc:  denied  { write } for  pid=5762 comm="aws-efs-csi-dri" name="efs" dev="tmpfs" ino=21031 scontext=system_u:system_r:container_t:s0 tcontext=system_u:object_r:etc_t:s0 tclass=dir permissive=0`

As it turns out, this is another case of #1111. 

The issue is that a change to the EFS CSI driver was incompatible with Bottlerocket. An issue was opened for the driver https://github.com/kubernetes-sigs/aws-efs-csi-driver/issues/246 and it looks like a fix PR is open https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/247

I'll look for a work-around before that PR lands.

**Comment by caoruidong** [comment] 2020-11-24 07:08
@jackie-JD I cannot find you too. You can try my id again, I open it just now.

**Comment by jackie-JD** [comment] 2020-11-24 10:20
OK,  thanks. Hope to get you good news.

**Comment by webern** [comment] 2020-11-24 15:55
I have re-opened #1111 and will mark this as a duplicate.

**Comment by webern** [comment] 2020-11-25 03:52
I managed to get past the avc denial with a patched version of the csi driver and found that we have a missing dependency. I'm going to describe that on #1111 and use that to track a feature request for EFS support. I'm going to close this issue as a duplicate but feel free to re-open if you have additional (non-EFS) questions. For EFS-tracking let's use #1111. Thank you!

**Closed as completed** 2020-11-27 18:45 UTC
Labels: type/bug, area/kubernetes

**Comment by jackie-JD** [comment] 2020-11-28 02:42
OK, got it. Thank you.
