### ISSUE TITLE
nvidia-variant random nvidia-device-plugin failures on boot-time

### ISSUE THREAD

**Issue by sanjinp** [bottlerocket-os/bottlerocket#3132] opened 2023-05-19 10:14 UTC
We are using EKS with managed node-groups, current version: 1.24 (same issue perceived on 1.23)
Our GPU instances are scaled for handling some rendering Jobs by autoscaler. As we tend to scale multiple instances at the same time, some of them does not have gpu exposed, i.e.
```
Capacity:
  attachable-volumes-aws-ebs:  39
  cpu:                         4
  ephemeral-storage:           41261776Ki
  hugepages-1Gi:               0
  hugepages-2Mi:               0
  memory:                      16061316Ki
  nvidia.com/gpu:              0
  pods:                        29
Allocatable:
  attachable-volumes-aws-ebs:  39
  cpu:                         3920m
  ephemeral-storage:           36953110875
  hugepages-1Gi:               0
  hugepages-2Mi:               0
  memory:                      15371140Ki
  nvidia.com/gpu:              0
  pods:                        29
```
This rate seem random, ranging of 10%-40% failed occurrences. Meaning that usually for new 6 GPU nodes `g4dn.xlarge` autoscaler goes up to 10 nodes until it satisfies Pod requirements. So remaining with failed nvidia-device-plugin gets deleted. However, this is currently not scalable, and adds to Pod start time significantly.
**Image I'm using:**
OS Image:                   Bottlerocket OS 1.14.0 (aws-k8s-1.24-nvidia)
AWS EKS Cluster       1.24

**What I expected to happen:**
integrated nvidia-device-plugin to expose availability of GPU card to kubernetes
```
Capacity:
  attachable-volumes-aws-ebs:  39
  cpu:                         4
  ephemeral-storage:           41261776Ki
  hugepages-1Gi:               0
  hugepages-2Mi:               0
  memory:                      16061316Ki
  nvidia.com/gpu:              1
  pods:                        29
Allocatable:
  attachable-volumes-aws-ebs:  39
  cpu:                         3920m
  ephemeral-storage:           36953110875
  hugepages-1Gi:               0
  hugepages-2Mi:               0
  memory:                      15371140Ki
  nvidia.com/gpu:              1
  pods:                        29
```
```
nvidia-k8s-device-plugin.service - Start NVIDIA kubernetes device plugin
     Loaded: loaded (/x86_64-bottlerocket-linux-gnu/sys-root/usr/lib/systemd/system/nvidia-k8s-device-plugin.service; enabled; vendor preset: enabled)
     Active: active (running) since Fri 2023-05-19 07:04:30 UTC; 3h 3min ago
   Main PID: 1449 (nvidia-device-p)
      Tasks: 9 (limit: 18812)
     Memory: 62.2M
     CGroup: /system.slice/nvidia-k8s-device-plugin.service
             └─ 1449 /usr/bin/nvidia-device-plugin nvidia-k8s-device-plugin.service - Start NVIDIA kubernetes device plugin
     Loaded: loaded (/x86_64-bottlerocket-linux-gnu/sys-root/usr/lib/systemd/system/nvidia-k8s-device-plugin.service; enabled; vendor preset: enabled)
     Active: active (running) since Fri 2023-05-19 07:04:30 UTC; 3h 3min ago
   Main PID: 1449 (nvidia-device-p)
      Tasks: 9 (limit: 18812)
     Memory: 62.2M
     CGroup: /system.slice/nvidia-k8s-device-plugin.service
             └─ 1449 /usr/bin/nvidia-device-plugin
```
**What actually happened:**
```
Capacity:
  attachable-volumes-aws-ebs:  39
  cpu:                         4
  ephemeral-storage:           41261776Ki
  hugepages-1Gi:               0
  hugepages-2Mi:               0
  memory:                      16061316Ki
  nvidia.com/gpu:              0
  pods:                        29
Allocatable:
  attachable-volumes-aws-ebs:  39
  cpu:                         3920m
  ephemeral-storage:           36953110875
  hugepages-1Gi:               0
  hugepages-2Mi:               0
  memory:                      15371140Ki
  nvidia.com/gpu:              0
  pods:                        29
```
```
May 19 07:49:42 ip-10-40-52-4.eu-west-1.compute.internal kubelet[1417]: Error: failed to run Kubelet: unable to determine runtime API version: rpc error: code = Unknown desc = server is not initialized yet
May 19 07:49:42 ip-10-40-52-4.eu-west-1.compute.internal systemd[1]: kubelet.service: Main process exited, code=exited, status=1/FAILURE
May 19 07:49:42 ip-10-40-52-4.eu-west-1.compute.internal systemd[1]: kubelet.service: Failed with result 'exit-code'.
May 19 07:49:42 ip-10-40-52-4.eu-west-1.compute.internal systemd[1]: Failed to start Kubelet.
May 19 07:49:42 ip-10-40-52-4.eu-west-1.compute.internal systemd[1]: Dependency failed for Start NVIDIA kubernetes device plugin.
May 19 07:49:42 ip-10-40-52-4.eu-west-1.compute.internal systemd[1]: nvidia-k8s-device-plugin.service: Job nvidia-k8s-device-plugin.service/start failed with result 'dependency'.
May 19 07:49:42 ip-10-40-52-4.eu-west-1.compute.internal systemd[1]: Reached target Multi-User System.
```
And it seems that it never tries to restart it, as kubelet gets started eventually.
**How to reproduce the problem:**
Run multiple `g4dn.xlarge` EKS instances and check availability of `nvidia.com/gpu`

**Comment by jpmcb** [comment] 2023-05-19 15:52
Hi @sanjinp - thanks for opening this issue and surfacing this.

> We are using EKS with managed node-groups ... Our GPU instances are scaled for handling some rendering Jobs by autoscaler. 

Can you tell me more about what's doing the auto-scaling? Is this using Karpenter to auto-scale based on workloads?

Are you able to share abit of your configuration yaml so I can try to reproduce this issue? Thanks!

**Comment by arnaldo2792** [comment] 2023-05-19 23:11
I think we may have to change the type of dependency we declared on `kubelet.service`, right now we use `BindsTo` but probably it will be best to use `Requires`, mainly because of this:

>  with or without specifying After=, this unit will be stopped (or restarted) if one of the other units is explicitly stopped (or restarted).

Compared to `BindsTo`:

> In this case, the unit bound to strictly has to be in active state for this unit to also be in active state.

I guess with `Requires`, systemd will restart the device plugin whenever the kubelet is restarted(?), which is what is missing with `BindsTo`.

**Comment by sanjinp** [comment] 2023-05-22 06:54
Hi @jpmcb - sure I'll be happy to add more info on this.
we are using cluster-autoscaler deployed by helm chart:
 ```
 - name: cluster-autoscaler
    version: 9.27.0
    repository: "@autoscaler"
```
So flow is: `keda -> Pod -> cluster-autoscaler`, and it does it's job well
On the other hand, managed-node group is handled by [terraform module](https://registry.terraform.io/modules/terraform-aws-modules/eks/aws/18.3.1)
So setup for this particular node-group looks like this:
```
        "gpu" = {
          min_size             = 0
          max_size             = 50
          desired_size         = 0
          key_name             = aws_key_pair.kubernetes[0].key_name
          instance_types       = ["g4dn.xlarge"]
          bootstrap_extra_args = <<-EOT
            [settings.boot.kernel-parameters]
            "crashkernel" = [
              "2G-:256M",
            ]
            [settings.kernel.sysctl]
            "net.core.rmem_max" = "16777216"
            "net.core.wmem_max" = "16777216"
            "kernel.core_pattern" = "/core-dumps/core-%p.%h.%t"
            [settings.ntp]
            "time-servers" = [
              "169.254.169.123",
              "time.google.com"
            ]
            [settings.kubernetes]
            "image-gc-low-threshold-percent" = "85"
            "image-gc-high-threshold-percent" = "90"
          EOT
          ami_type             = "BOTTLEROCKET_x86_64_NVIDIA"
          block_device_mappings = {
            xvdb = {
              device_name = "/dev/xvdb"
              ebs = {
                volume_size           = 40
                volume_type           = "gp3"
                throughput            = 125
                snapshot_id           = data.aws_ebs_snapshot.gpu[0].id <- happens regardless using prebuilt snapshot or not
                encrypted             = true
                delete_on_termination = true
              }
            }
          }
          labels = {
            "cluster"              = var.name
            "instance-class"       = "accelerated-computing"
            "node.kubernetes/role" = "gpu"
            "dedicated"            = "gpu"
          }
          taints = {
            dedicated = {
              key    = "dedicated"
              value  = "gpu"
              effect = "NO_SCHEDULE"
            }
          }
          subnet_ids = var.private_subnets_ids
        }
```

**Comment by stmcginnis** [comment] 2023-05-22 10:55
I don't know enough about the Terraform module, but it seems odd to specify `min_size = 0` and `desired_size = 0` for the `gpu` section. Have you tried setting `min_size = 1`?

**Comment by sanjinp** [comment] 2023-05-22 14:42
@stmcginnis thank you for your comment, it is not odd, that is our use case, we don’t want gpus running all the time. And that is something that cluster-autoscaler handles. It is normal case to have desired and min set to zero for job-like workloads.
I’ve pasted additional info for clarity, but don’t let them distract you from my first post, which is unrelated to how we scale nodes, the point is when noden is scaled nvidia-device-plugin fails to load randomly. And that is not influenced neither by autoscaler nor terraform

**Comment by jpmcb** [comment] 2023-05-22 15:11
> I think we may have to change the type of dependency we declared on kubelet.service, right now we use BindsTo but probably it will be best to use Requires, mainly because of this:

I think @arnaldo2792 is right: looking at your kubelet logs, the client is failing to start and then bails on attempting to start the nvidia driver. Re-arranging the kublet service dependencies to correctly have the nvidia driver as a requirement would get that bit of software to re-initialize and start the drivers when kublet inevitably rolls.

I tried reproducing this issue with `eksctl` and manually setting the auto-scaling group for nvidia instances from 0 to 10 (and then back to 0, so on and so forth). But I couldn't get it to reproduce. It's odd that you're getting kublet errors that look like the api-server is not ready or that your client hasn't attached to the control plane: `Error: failed to run Kubelet: unable to determine runtime API version: rpc error: code = Unknown desc = server is not initialized yet` - how many jobs / instances are being dynamically spun up in this way? What's the workload like on this cluster? If you already have a working control plane, maybe this is a scaling issue as well where the API server can't handle all requests as fast as new nodes are being spun up?

**Comment by sanjinp** [comment] 2023-05-23 06:44
@jpmcb this happens on a small scale, e.g. we spin up 3 nodes from 0, and 1 of them remains in a Pending state (logs in first  post). And AS goes to 5 to satisfy Pod requirement, where it'll succeed eventually with new instances. We are running single render job / Instance. So I doubt that is could be related to overhauling API server. But yes I agree with you that it is odd to receive these errors and that's where we're stuck ATM. I'll be happy to give you any more info that potentially could lead to root cause, do you need any beside what I've pasted?

**Comment by rpkelly** [comment] 2023-05-23 23:30
@sanjinp I have a few followup questions to help us reproduce this:

* Have you run this setup on a previous version of Bottlerocket?

* Are you running any bootstrap containers on node launch? It's possible that extra load might be the key to reproduce this issue.

* What region are you running in?

* Is there anything unique about your pod setup that might be important for us to try and reproduce?

**Comment by bcressey** [comment] 2023-05-24 00:49
@sanjinp thanks for the report.

It looks like there are two issues here:
* `kubelet` sometimes starts [before `containerd` has fully initialized CRI](https://github.com/containerd/containerd/blob/5997a6589686479e0bf7074218bd7bddf09d2d8f/pkg/cri/instrument/instrumented_service.go#L66), causing `kubelet` to fail and be restarted
* `nvidia-k8s-device-plugin.service` has a `BindsTo` dependency on `kubelet`, so this failure causes `systemd` to stop it, after which it is not restarting

The second error should be easier to fix since [the device plugin tolerates `kubelet` restarts](https://github.com/NVIDIA/k8s-device-plugin/blob/ac6730dd57754c4aba4dc95cb463609c8eb7bc65/cmd/nvidia-device-plugin/main.go#LL197C1-L197C1). @arnaldo2792 is testing a fix for this.

The first error shouldn't be happening since `containerd.service` is set to `Type=notify`, so [containerd only sends that notification when it's ready](https://github.com/containerd/containerd/blob/5997a6589686479e0bf7074218bd7bddf09d2d8f/cmd/containerd/command/main.go#L273). Yet somehow we're seeing the service start without CRI being initialized - perhaps because CRI is a plugin and doesn't "count" for the purposes of `containerd` itself being ready.

We'll need to discuss upstream with the containerd and kubelet folks to see what the right path forward is - either `kubelet` should tolerate this condition and retry, or `containerd` should not notify `systemd` that it's ready until CRI is ready, or something along those lines. Handling this by restarting the service seems to work - apart from the device plugin dependency - but isn't very elegant.

**Comment by sanjinp** [comment] 2023-05-24 14:38
Hi, I have an update, in the end it looks like that my root cause was related to using prebuilt volume snapshot.
Triggered by @jpmcb comment that he couldn't reproduce an issue, I took step back and removed our volume snapshots to have similar setup as he did during testing, and I couldn't reproduce it either on current AMI (Bottlerocket OS 1.14.0), can not confirm is back for older one, as we don't have them in the system anymore.

1. Had working Node currently holding the downloaded images
2. removed those deployments
3. Created volume snapshot from Node
4. Set snapshots to be used for newly created GPU Nodes (encrypted, same capacity, on same cluster)

However, I lived in belief that we have defined filesystem separation for OS related stuff, and additional attached volume created from snapshot (which was holding our heavy base images, so we don't have to pull it every time). But that doesn't seem to be the case. We seem to have some lingering stuff that comes with the snapshotting, conflicting with kubelet.
So putting it in here FYI.
And it's kinda new issue??, however thank you very much for all of your support! Documentation doesn't seem to cover our case and if you have some guides from you gurus I would much appreciate it, and for others who'll probably stumble in similar situation with similar use case.
So snapshotting randomly worked this way

**Comment by bcressey** [comment] 2023-05-24 15:46
On first boot with an empty snapshot, before `kubelet` is started, [`host-ctr` pulls the pause container image](https://github.com/bottlerocket-os/bottlerocket/blob/develop/packages/kubernetes-1.27/prestart-pull-pause-ctr.conf). That will usually take a few seconds, which I suspect is what gives CRI time to be initialized before `kubelet` tries to access the server.

When using a pre-populated snapshot, the pause container image will already be cached, so `kubelet` starts almost immediately. I suspect we're hitting this failure / restart mode any time we have a snapshot like that attached, but it's only visible on GPU nodes because of the incorrect device plugin dependency.

**Closed as completed** 2023-05-24 16:42 UTC
Labels: type/bug, status/in-progress
