### ISSUE TITLE
Unexpected connection refused when running fluent-bit on 1.20 cluster

### ISSUE THREAD

**Issue by gthao313** [bottlerocket-os/bottlerocket#1628] opened 2021-06-23 15:47 UTC
**Image I'm using:**
ami-00e7ac29da78d893c

**What I expected to happen:**
Successfully connect to port and fluent-bit starts to work
Example:
```
sh-4.2# while curl localhost:2020; do echo pass; done
{"fluent-bit":{"version":"1.7.9","edition":"Community","flags":["FLB_HAVE_PARSER","FLB_HAVE_RECORD_ACCESSOR","FLB_HAVE_STREAM_PROCESSOR","FLB_HAVE_TLS","FLB_HAVE_OPENSSL","FLB_HAVE_AWS","FLB_HAVE_SIGNV4","FLB_HAVE_SQLDB","FLB_HAVE_METRICS","FLB_HAVE_HTTP_SERVER","FLB_HAVE_SYSTEMD","FLB_HAVE_FORK","FLB_HAVE_TIMESPEC_GET","FLB_HAVE_GMTOFF","FLB_HAVE_UNIX_SOCKET","FLB_HAVE_PROXY_GO","FLB_HAVE_JEMALLOC","FLB_HAVE_LIBBACKTRACE","FLB_HAVE_REGEX","FLB_HAVE_UTF8_ENCODER","FLB_HAVE_LUAJIT","FLB_HAVE_C_TLS","FLB_HAVE_ACCEPT4","FLB_HAVE_INOTIFY"]}}pass
```

**What actually happened:**
```
Failed to connect to localhost port 2020: Connection refused
```

**How to reproduce the problem:**
1. Setting up a 1.20 cluster in eu-central-1
2. Launching bottlerocket instance
3. ```kubectl run --image public.ecr.aws/aws-observability/aws-for-fluent-bit:2.16.0 --command -- sh```
4. ```kubectl exec -ti sh -- sh```
5. ```/fluent-bit/bin/fluent-bit -H -i cpu -o null &```
6. ```while curl localhost:2020; do echo pass; done```

**Comment by snstanton** [comment] 2021-06-24 16:03
Do you have any idea what might be going on?  This is blocking our cluster rollout on 1.20.  Any suggestions for a workaround would be great.  Otherwise, we're looking at having to roll back the cluster to 1.19.

**Comment by jhaynes** [comment] 2021-06-24 22:58
We don't have a root cause yet but our on-call @gthao313 is working on figuring out the cause and a work around.

**Comment by snstanton** [comment] 2021-06-25 00:48
FYI, what I'm doing at the moment is disabling the lifecycle checks.  The pod appears to function normally except for the http port that handles the readiness/liveness check.

**Comment by gthao313** [comment] 2021-06-25 01:13
Hey @snstanton. Thanks for your information. We are still investigating on this issue. but I can give you some updates. To target what caused this issue, I was running different variant bottlerocket images and connect to 1.20 cluster, and experiment results tell me that bottlerocket-aws-k8s-1.20 would return the same error `connection refused` as you got, and rest variants worked as expected. Therefore, we target the root cause might be kernel version and cluster version. I implemented a test to prove if kernel version really cause this issue, which was building an bottlerocket-aws-k8s-1.20 image with 5.4 kernel (old version, current is 5.10) and starting fluent-bit on it. However, it still failed with `connection refused`. Hence, I think the root cause might be `1.20 kubelet` . I'm going to do more tests to prove if `1.20  kubelet` is the root cause here. I'll update to you more information once I finish the test Thanks! : )

**Comment by snstanton** [comment] 2021-06-28 17:43
Do you have any idea what is triggering the issue?  I'm trying to decide if this is going to affect any other pods aside from fluent-bit.

**Comment by gthao313** [comment] 2021-06-28 20:04
Hey @snstanton.  After comparing 1.19 variant kubeconfigs to 1.20 variant kubeconfigs, we found he root cause was `cpuManagerPolicy: "static"`. We still investigate on how it affects fluent-bit. Unfortunately, we did not expose `cpuManagerPolicy` as a setting, so currently we suggest you to rollback or pause your 1.20 deployment.  If we have any updates, we will let you know. Thanks : )

**Comment by bcressey** [comment] 2021-06-29 15:05
What's happening is that the epoll loop in the embedded web server (monkey) is getting an EINTR that it doesn't handle properly:
```
[pid  5747] 21:36:57 epoll_wait(27,  <unfinished ...>
[pid  5747] 21:36:57 <... epoll_wait resumed> 0x7f750f20c000, 256, -1) = -1 EINTR (Interrupted system call)
[pid  5747] 21:36:57 epoll_wait(27,  <unfinished ...>
[pid  5747] 21:36:57 <... epoll_wait resumed> [{EPOLLIN, {u32=253976576, u64=140140741877760}}], 256, -1) = 1
[pid  5745] 21:36:57 futex(0x7f750fffe9d0, FUTEX_WAIT, 5747, NULL <unfinished ...>
[pid  5747] 21:36:57 read(28, "\0\0\356\377\0\0\0\0", 8) = 8
[pid  5747] 21:36:57 close(34)          = 0
[pid  5747] 21:36:57 close(30)          = 0
[pid  5747] 21:36:57 close(27)          = 0
[pid  5747] 21:36:57 madvise(0x7f750f239000, 16384, MADV_DONTNEED) = 0
[pid  5747] 21:36:57 madvise(0x7f750f247000, 102400, MADV_DONTNEED) = 0
[pid  5747] 21:36:57 madvise(0x7f750f201000, 40960, MADV_DONTNEED) = 0
[pid  5747] 21:36:57 madvise(0x7f750f20c000, 172032, MADV_DONTNEED) = 0
[pid  5747] 21:36:57 madvise(0x7f750f7fe000, 8327168, MADV_DONTNEED) = 0
[pid  5747] 21:36:57 exit(0)            = ?
[pid  5747] 21:36:57 +++ exited with 0 +++
```

While looking at the k8s source code I noticed that there's another value, cpuManagerReconcilePeriod, which is set by default to 10s. On a hunch I put `cpuManagerReconcilePeriod: 10m` into the kubelet config, and the web server was up for 9 minutes and 40 seconds until it went away.

Something in the reconciliation path causes an interaction that triggers the kernel to interrupt the epoll loop unexpectedly. The application should retry, but doesn't, and exits instead.

For the 1.20 and 1.21 builds, we need to put together an update that will make this setting configurable, and migrate back to  the old default on upgrade. Separately, we need to figure out where to add the EINTR check in fluent-bit or monkey so that it doesn't exit unexpectedly.

**Comment by gabegorelick** [comment] 2021-06-30 16:33
Title should probably be edited. I see similar behavior in us-east-1. It sounds like the consensus is that `cpuManagerPolicy` is the issue and eu-central-1 isn't salient.

Happy to provide more info if needed.

**Comment by gabegorelick** [comment] 2021-06-30 18:49
I think this issue is larger than just Fluent Bit's embedded HTTP server not working. I'm seeing Fluent Bit stop processing logs completely after a few minutes (similar to https://github.com/fluent/fluent-bit/issues/3014 or https://github.com/fluent/fluent-bit/issues/3518). Downgrading to Bottlerocket 1.19 fixes it.

**Comment by gthao313** [comment] 2021-07-14 18:40
All, we have just released Bottlerocket 1.1.3. In this version the default of `cpu-manager-policy` was set back to “none”, which can solve the problem that unexpected connection refused when running fluent-bit on 1.20 cluster.

**Comment by gabegorelick** [comment] 2021-07-14 18:42
I can confirm that upgrading to 1.1.3 fixed the issues with Fluent Bit that I was seeing.

**Comment by zmrow** [comment] 2021-07-22 15:44
Since 1.1.3 appears to fix the issue I'll close this.  Feel free to re-open if this continue to be a problem!

**Closed as completed by zmrow** 2021-07-22 15:44 UTC
Labels: type/bug, area/kubernetes
